apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aigateway-console.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aigateway-console.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aigateway-console-promtail.name" . }}
  namespace: {{ .Release.Namespace }}
